const CHANNEL_DIRECT_MESSAGES_CLIENT = "CHANNEL_DIRECT_MESSAGES_CLIENT";
const CHANNEL_DIRECT_MESSAGES_SERVER = "CHANNEL_DIRECT_MESSAGES_SERVER";

module.exports = {
  CHANNEL_DIRECT_MESSAGES_CLIENT,
  CHANNEL_DIRECT_MESSAGES_SERVER,
};
