const CHANNEL_DIRECT_MESSAGES_CLIENT = "CHANNEL_DIRECT_MESSAGES_CLIENT";
const CHANNEL_DIRECT_MESSAGES_SERVER = "CHANNEL_DIRECT_MESSAGES_SERVER";

const USER_NOTIFICATION_FROM_CLIENT_TO_SERVER =
  "USER_NOTIFICATION_FROM_CLIENT_TO_SERVER";
const USER_NOTIFICATION_FROM__SERVER_TO_CLIENT =
  "USER_NOTIFICATION_FROM__SERVER_TO_CLIENT";

module.exports = {
  CHANNEL_DIRECT_MESSAGES_CLIENT,
  CHANNEL_DIRECT_MESSAGES_SERVER,
  USER_NOTIFICATION_FROM_CLIENT_TO_SERVER,
  USER_NOTIFICATION_FROM__SERVER_TO_CLIENT,
};
